name: dependent jobs

on: push

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date

  job_on_windows:
    name: A windows job
    runs-on: windows-latest
    steps:
      - name: First step in windows job
        run: date

  job_on_macos:
    name: A job that runs on Macos
    needs: [job_on_ubuntu, job_on_windows]
    runs-on: macos-latest
    steps:
      - run: pwd
      - name: new step
        run: ls
      - name: another step
        run: ps -aux

  Final_job:
    name: A final job
    needs: job_on_macos
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World!!
